# Conexão direta com o banco online do Render (Sem depender das caixas do site)
spring.datasource.url=jdbc:postgresql://vagas_db_wfbi_user:W0ny7dOUSNQIHSjzyjImh6Ls7rdi1ZT6@://render.com
spring.datasource.username=vagas_db_wfbi_user
spring.datasource.password=W0ny7dOUSNQIHSjzyjImh6Ls7rdi1ZT6

# Porta dinâmica para o servidor de hospedagem
server.port=${PORT:8080}

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
